# config.ini

data:
  task: image
  path: D:\Datasets\ForestrySecurity\insects98
  num_classes: 98

model:
  arch: fresnet18
  kwargs:
    pretrained: True
    num_classes: 98

learning: 
  # general
  epochs: 90
  batch_size: 32

loss: 
  arch: CrossEntropyLoss
  kwargs: 

optimizer: 
  arch: SGD
  kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 1.0e-4

lr_scheduler: 
  arch: StepLR
  kwargs:
    step_size: 30
    gamma: 0.1

speed: 
  dataload_workers: 2
  cudnn_benchmark: True   # cudnn-benchmark: speedup for fixed-size input